### ISSUE TITLE
Update API to conform with RedisAI changes

### ISSUE THREAD

**Issue by mellis13** [CrayLabs/SmartRedis#133]
# Description
RedisAI has deprecated several API functions and added some additional functionality to the replacement functions.  The SmartRedis API should be updated to conform with these changes.

# Justification
The additional features of the API  are useful for users, and the existing RedisAI API will be removed in future releases.

# Implementation Strategy
The following API changes are needed:

- [ ]  ``ModelSet`` changed to ``ModelStore``.  The ``input_count`` and ``output_count``  fields will need to be added to the command execution.
- [ ]  ``ScriptSet`` changed to ``ScriptStore``.  ``ScriptStore`` has an additional parameter ``ENTRY_POINTS`` which will need to be added to the SmartRedis API.
- [ ]  ``ModelRun`` changed to ``ModelExecute``.  The ``input_count`` and ``output_count``  fields will need to be added to the command execution.
- [ ]  `` ScriptRun`` changed to ``ScriptExecute``.  The additional parameters ``ARGS`` and ``TIMEOUT`` need to be added to the SmartRedis API.  Also, the ``KEYS`` field needs to be added to the command execution.

**Comment by billschereriii** [comment]
Changing `script_set()` to use `AI.SCRIPTSTORE` requires breaking changes to both the SmartRedis API and to user scripts (details below). For this reason, PR #229 only addresses the update for `model_set()` and `model_run()`.

Details: 
1. `AI.SCRIPTSTORE` requires enumeration of script entry points, where `AI.SCRIPTSET` did not. While we could try to parse the user's script to identify these entry points, that is a comparatively large effort that would only serve as a partial solution because of item 2, next:
2. The script entry point functions s for `AI.SCRIPTSTORE`/`AI.SCRIPTEXECUTE` now have a required signature of `def entry_point(tensors: List[Tensor], keys: List[str], args: List[str])`. Users will need to update their scripts to conform to this new interface.
