### ISSUE TITLE
Question about SmartRedis clients

### ISSUE THREAD

**Issue by benjha** [CrayLabs/SmartRedis#144]
Hi SmartSim team,

From your documentation and examples, I noted the C++  `Client` function does not need the address/port  of the `Orchestrator`, while the python client does, otherwise running a python client without address/port exits with the next error:

```
smartredis.error.RedisConnectionError: Could not connect to database. $SSDB not set
```

I haven't try it yet, but does this implies C++ clients cannot be used as "stand alone" analysis codes, and only can be used as simulation codes executed via an `Experiment` ?

Thanks,

**Comment by mellis13** [comment]
Hello,

The SmartRedis clients do not have to be used with SmartSim, but SmartSim automates the work of launching a Redis database (either cluster or non-cluster).  If you have launched your own database, the SmartRedis clients can be used without SmartSim.

Regarding the error message that you posted, all of the SmartRedis clients (Python/C/C++/Fortran) read the environment variable ``SSDB`` for the address and port in order to connect to the database.  Before executing your code containing the SmartRedis client, you can set the environment variable as follows (substitute in the correct host and port into the command below):

```bash
export SSDB="127.0.0.1:6379"
```
The python client includes an additional constructor that takes in an address and port which overrides the value of the ``SSDB`` environment variable.

**Comment by benjha** [comment]
Thanks, 

I totally missed SSDB reference in the documentation:

https://www.craylabs.org/docs/sr_runtime.html?highlight=ssdb#setting-redis-database-location
