### ISSUE TITLE
Make clean clobbers testing dependencies

### ISSUE THREAD

**Issue by billschereriii** [CrayLabs/SmartRedis#176]
# Description
Performing a `make clean` operation clobbers the catch library.

# How to reproduce
`make test-deps; make clean; make test` will show that catch is installed and then not present when the tests are attempted.

# Expected behavior
`make test` should succeed following `make clean` without needing to run `make test-deps` first.

**Comment by billschereriii** [comment]
Note: `make clobber` should remove third-party dependencies. Just not `make clean`.

**Comment by mellis13** [comment]
@MattToast I looked into this, and I think the easiest approach is to just ``git clone`` the catch version we want instead of downloading the single header file.  While the single header file is nice, the next major version Catch is moving away from single header file approach (https://github.com/catchorg/Catch2/releases/tag/v3.0.0-preview4), so we might as well do it now.  We will need to update include directories for the unit tests.
